FROM android-sdk
curl https://dl.google.com/dl/android/studio/ide-zips/1.0.1/android-studio-ide-135.1641136-linux.zip -o /tmp/android-studio-ide-135.1641136-linux.zip && unzip /tmp/android-studio-ide-135.1641136-linux.zip -d /usr/local && rm /tmp/android-studio-ide-135.1641136-linux.zip
ENTRYPOINT /usr/local/android-studio/bin/studio.sh
